// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/matheusj989/wagering-wallet-service/internal/application/port (interfaces: Clock,IDGenerator,WalletEventNotifier,Failpoint,WageringMetrics,ReconciliationMetrics,ReferenceMetrics,OutboxMetrics,ConsumerMetrics)
//
// Generated by this command:
//
//	mockgen -destination=port.go -package=mocks github.com/matheusj989/wagering-wallet-service/internal/application/port Clock,IDGenerator,WalletEventNotifier,Failpoint,WageringMetrics,ReconciliationMetrics,ReferenceMetrics,OutboxMetrics,ConsumerMetrics
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	messaging "github.com/matheusj989/wagering-wallet-service/internal/domain/messaging"
	gomock "go.uber.org/mock/gomock"
)

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockIDGenerator) New() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockIDGeneratorMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockIDGenerator)(nil).New))
}

// MockWalletEventNotifier is a mock of WalletEventNotifier interface.
type MockWalletEventNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockWalletEventNotifierMockRecorder
	isgomock struct{}
}

// MockWalletEventNotifierMockRecorder is the mock recorder for MockWalletEventNotifier.
type MockWalletEventNotifierMockRecorder struct {
	mock *MockWalletEventNotifier
}

// NewMockWalletEventNotifier creates a new mock instance.
func NewMockWalletEventNotifier(ctrl *gomock.Controller) *MockWalletEventNotifier {
	mock := &MockWalletEventNotifier{ctrl: ctrl}
	mock.recorder = &MockWalletEventNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletEventNotifier) EXPECT() *MockWalletEventNotifierMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWalletEventNotifier) Send(ctx context.Context, event messaging.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockWalletEventNotifierMockRecorder) Send(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWalletEventNotifier)(nil).Send), ctx, event)
}

// MockFailpoint is a mock of Failpoint interface.
type MockFailpoint struct {
	ctrl     *gomock.Controller
	recorder *MockFailpointMockRecorder
	isgomock struct{}
}

// MockFailpointMockRecorder is the mock recorder for MockFailpoint.
type MockFailpointMockRecorder struct {
	mock *MockFailpoint
}

// NewMockFailpoint creates a new mock instance.
func NewMockFailpoint(ctrl *gomock.Controller) *MockFailpoint {
	mock := &MockFailpoint{ctrl: ctrl}
	mock.recorder = &MockFailpointMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailpoint) EXPECT() *MockFailpointMockRecorder {
	return m.recorder
}

// Hit mocks base method.
func (m *MockFailpoint) Hit(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Hit", name)
}

// Hit indicates an expected call of Hit.
func (mr *MockFailpointMockRecorder) Hit(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hit", reflect.TypeOf((*MockFailpoint)(nil).Hit), name)
}

// MockWageringMetrics is a mock of WageringMetrics interface.
type MockWageringMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockWageringMetricsMockRecorder
	isgomock struct{}
}

// MockWageringMetricsMockRecorder is the mock recorder for MockWageringMetrics.
type MockWageringMetricsMockRecorder struct {
	mock *MockWageringMetrics
}

// NewMockWageringMetrics creates a new mock instance.
func NewMockWageringMetrics(ctrl *gomock.Controller) *MockWageringMetrics {
	mock := &MockWageringMetrics{ctrl: ctrl}
	mock.recorder = &MockWageringMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWageringMetrics) EXPECT() *MockWageringMetricsMockRecorder {
	return m.recorder
}

// ConcurrencyConflict mocks base method.
func (m *MockWageringMetrics) ConcurrencyConflict(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConcurrencyConflict", reason)
}

// ConcurrencyConflict indicates an expected call of ConcurrencyConflict.
func (mr *MockWageringMetricsMockRecorder) ConcurrencyConflict(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConcurrencyConflict", reflect.TypeOf((*MockWageringMetrics)(nil).ConcurrencyConflict), reason)
}

// IdempotencyConflict mocks base method.
func (m *MockWageringMetrics) IdempotencyConflict(origin, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IdempotencyConflict", origin, reason)
}

// IdempotencyConflict indicates an expected call of IdempotencyConflict.
func (mr *MockWageringMetricsMockRecorder) IdempotencyConflict(origin, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdempotencyConflict", reflect.TypeOf((*MockWageringMetrics)(nil).IdempotencyConflict), origin, reason)
}

// IdempotentReplay mocks base method.
func (m *MockWageringMetrics) IdempotentReplay(origin string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IdempotentReplay", origin)
}

// IdempotentReplay indicates an expected call of IdempotentReplay.
func (mr *MockWageringMetricsMockRecorder) IdempotentReplay(origin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdempotentReplay", reflect.TypeOf((*MockWageringMetrics)(nil).IdempotentReplay), origin)
}

// ProcessingObserved mocks base method.
func (m *MockWageringMetrics) ProcessingObserved(origin, kind string, elapsed time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessingObserved", origin, kind, elapsed)
}

// ProcessingObserved indicates an expected call of ProcessingObserved.
func (mr *MockWageringMetricsMockRecorder) ProcessingObserved(origin, kind, elapsed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessingObserved", reflect.TypeOf((*MockWageringMetrics)(nil).ProcessingObserved), origin, kind, elapsed)
}

// TransactionSettled mocks base method.
func (m *MockWageringMetrics) TransactionSettled(kind, status, origin string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TransactionSettled", kind, status, origin)
}

// TransactionSettled indicates an expected call of TransactionSettled.
func (mr *MockWageringMetricsMockRecorder) TransactionSettled(kind, status, origin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionSettled", reflect.TypeOf((*MockWageringMetrics)(nil).TransactionSettled), kind, status, origin)
}

// MockReconciliationMetrics is a mock of ReconciliationMetrics interface.
type MockReconciliationMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockReconciliationMetricsMockRecorder
	isgomock struct{}
}

// MockReconciliationMetricsMockRecorder is the mock recorder for MockReconciliationMetrics.
type MockReconciliationMetricsMockRecorder struct {
	mock *MockReconciliationMetrics
}

// NewMockReconciliationMetrics creates a new mock instance.
func NewMockReconciliationMetrics(ctrl *gomock.Controller) *MockReconciliationMetrics {
	mock := &MockReconciliationMetrics{ctrl: ctrl}
	mock.recorder = &MockReconciliationMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciliationMetrics) EXPECT() *MockReconciliationMetricsMockRecorder {
	return m.recorder
}

// ReconciliationDivergence mocks base method.
func (m *MockReconciliationMetrics) ReconciliationDivergence() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReconciliationDivergence")
}

// ReconciliationDivergence indicates an expected call of ReconciliationDivergence.
func (mr *MockReconciliationMetricsMockRecorder) ReconciliationDivergence() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconciliationDivergence", reflect.TypeOf((*MockReconciliationMetrics)(nil).ReconciliationDivergence))
}

// MockReferenceMetrics is a mock of ReferenceMetrics interface.
type MockReferenceMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockReferenceMetricsMockRecorder
	isgomock struct{}
}

// MockReferenceMetricsMockRecorder is the mock recorder for MockReferenceMetrics.
type MockReferenceMetricsMockRecorder struct {
	mock *MockReferenceMetrics
}

// NewMockReferenceMetrics creates a new mock instance.
func NewMockReferenceMetrics(ctrl *gomock.Controller) *MockReferenceMetrics {
	mock := &MockReferenceMetrics{ctrl: ctrl}
	mock.recorder = &MockReferenceMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReferenceMetrics) EXPECT() *MockReferenceMetricsMockRecorder {
	return m.recorder
}

// ReferenceFailed mocks base method.
func (m *MockReferenceMetrics) ReferenceFailed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReferenceFailed")
}

// ReferenceFailed indicates an expected call of ReferenceFailed.
func (mr *MockReferenceMetricsMockRecorder) ReferenceFailed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReferenceFailed", reflect.TypeOf((*MockReferenceMetrics)(nil).ReferenceFailed))
}

// ReferencePending mocks base method.
func (m *MockReferenceMetrics) ReferencePending(count int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReferencePending", count)
}

// ReferencePending indicates an expected call of ReferencePending.
func (mr *MockReferenceMetricsMockRecorder) ReferencePending(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReferencePending", reflect.TypeOf((*MockReferenceMetrics)(nil).ReferencePending), count)
}

// ReferenceRetried mocks base method.
func (m *MockReferenceMetrics) ReferenceRetried() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReferenceRetried")
}

// ReferenceRetried indicates an expected call of ReferenceRetried.
func (mr *MockReferenceMetricsMockRecorder) ReferenceRetried() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReferenceRetried", reflect.TypeOf((*MockReferenceMetrics)(nil).ReferenceRetried))
}

// MockOutboxMetrics is a mock of OutboxMetrics interface.
type MockOutboxMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxMetricsMockRecorder
	isgomock struct{}
}

// MockOutboxMetricsMockRecorder is the mock recorder for MockOutboxMetrics.
type MockOutboxMetricsMockRecorder struct {
	mock *MockOutboxMetrics
}

// NewMockOutboxMetrics creates a new mock instance.
func NewMockOutboxMetrics(ctrl *gomock.Controller) *MockOutboxMetrics {
	mock := &MockOutboxMetrics{ctrl: ctrl}
	mock.recorder = &MockOutboxMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxMetrics) EXPECT() *MockOutboxMetricsMockRecorder {
	return m.recorder
}

// OutboxPending mocks base method.
func (m *MockOutboxMetrics) OutboxPending(count int64, oldestAge time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutboxPending", count, oldestAge)
}

// OutboxPending indicates an expected call of OutboxPending.
func (mr *MockOutboxMetricsMockRecorder) OutboxPending(count, oldestAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxPending", reflect.TypeOf((*MockOutboxMetrics)(nil).OutboxPending), count, oldestAge)
}

// OutboxPublishAttempt mocks base method.
func (m *MockOutboxMetrics) OutboxPublishAttempt(result string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutboxPublishAttempt", result)
}

// OutboxPublishAttempt indicates an expected call of OutboxPublishAttempt.
func (mr *MockOutboxMetricsMockRecorder) OutboxPublishAttempt(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxPublishAttempt", reflect.TypeOf((*MockOutboxMetrics)(nil).OutboxPublishAttempt), result)
}

// MockConsumerMetrics is a mock of ConsumerMetrics interface.
type MockConsumerMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerMetricsMockRecorder
	isgomock struct{}
}

// MockConsumerMetricsMockRecorder is the mock recorder for MockConsumerMetrics.
type MockConsumerMetricsMockRecorder struct {
	mock *MockConsumerMetrics
}

// NewMockConsumerMetrics creates a new mock instance.
func NewMockConsumerMetrics(ctrl *gomock.Controller) *MockConsumerMetrics {
	mock := &MockConsumerMetrics{ctrl: ctrl}
	mock.recorder = &MockConsumerMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerMetrics) EXPECT() *MockConsumerMetricsMockRecorder {
	return m.recorder
}

// MessageDeadLettered mocks base method.
func (m *MockConsumerMetrics) MessageDeadLettered(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MessageDeadLettered", reason)
}

// MessageDeadLettered indicates an expected call of MessageDeadLettered.
func (mr *MockConsumerMetricsMockRecorder) MessageDeadLettered(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageDeadLettered", reflect.TypeOf((*MockConsumerMetrics)(nil).MessageDeadLettered), reason)
}

// MessageReceived mocks base method.
func (m *MockConsumerMetrics) MessageReceived() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MessageReceived")
}

// MessageReceived indicates an expected call of MessageReceived.
func (mr *MockConsumerMetricsMockRecorder) MessageReceived() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageReceived", reflect.TypeOf((*MockConsumerMetrics)(nil).MessageReceived))
}

// MessageRedelivered mocks base method.
func (m *MockConsumerMetrics) MessageRedelivered() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MessageRedelivered")
}

// MessageRedelivered indicates an expected call of MessageRedelivered.
func (mr *MockConsumerMetricsMockRecorder) MessageRedelivered() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageRedelivered", reflect.TypeOf((*MockConsumerMetrics)(nil).MessageRedelivered))
}

// MessageRetried mocks base method.
func (m *MockConsumerMetrics) MessageRetried() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MessageRetried")
}

// MessageRetried indicates an expected call of MessageRetried.
func (mr *MockConsumerMetricsMockRecorder) MessageRetried() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageRetried", reflect.TypeOf((*MockConsumerMetrics)(nil).MessageRetried))
}
