// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/matheusj989/wagering-wallet-service/internal/domain/repositories (interfaces: UnitOfWork,Registry,Wallet,Ledger,WagerTransaction,Inbox,Outbox)
//
// Generated by this command:
//
//	mockgen -destination=repositories.go -package=mocks github.com/matheusj989/wagering-wallet-service/internal/domain/repositories UnitOfWork,Registry,Wallet,Ledger,WagerTransaction,Inbox,Outbox
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	messaging "github.com/matheusj989/wagering-wallet-service/internal/domain/messaging"
	money "github.com/matheusj989/wagering-wallet-service/internal/domain/money"
	repositories "github.com/matheusj989/wagering-wallet-service/internal/domain/repositories"
	wagering "github.com/matheusj989/wagering-wallet-service/internal/domain/wagering"
	wallet "github.com/matheusj989/wagering-wallet-service/internal/domain/wallet"
	gomock "go.uber.org/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockUnitOfWork) Do(ctx context.Context, fn func(context.Context, repositories.Registry) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockUnitOfWorkMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockUnitOfWork)(nil).Do), ctx, fn)
}

// Read mocks base method.
func (m *MockUnitOfWork) Read(ctx context.Context, fn func(context.Context, repositories.Registry) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockUnitOfWorkMockRecorder) Read(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockUnitOfWork)(nil).Read), ctx, fn)
}

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// Inbox mocks base method.
func (m *MockRegistry) Inbox() repositories.Inbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inbox")
	ret0, _ := ret[0].(repositories.Inbox)
	return ret0
}

// Inbox indicates an expected call of Inbox.
func (mr *MockRegistryMockRecorder) Inbox() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inbox", reflect.TypeOf((*MockRegistry)(nil).Inbox))
}

// Ledger mocks base method.
func (m *MockRegistry) Ledger() repositories.Ledger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ledger")
	ret0, _ := ret[0].(repositories.Ledger)
	return ret0
}

// Ledger indicates an expected call of Ledger.
func (mr *MockRegistryMockRecorder) Ledger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ledger", reflect.TypeOf((*MockRegistry)(nil).Ledger))
}

// Outbox mocks base method.
func (m *MockRegistry) Outbox() repositories.Outbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Outbox")
	ret0, _ := ret[0].(repositories.Outbox)
	return ret0
}

// Outbox indicates an expected call of Outbox.
func (mr *MockRegistryMockRecorder) Outbox() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Outbox", reflect.TypeOf((*MockRegistry)(nil).Outbox))
}

// Transactions mocks base method.
func (m *MockRegistry) Transactions() repositories.WagerTransaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transactions")
	ret0, _ := ret[0].(repositories.WagerTransaction)
	return ret0
}

// Transactions indicates an expected call of Transactions.
func (mr *MockRegistryMockRecorder) Transactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transactions", reflect.TypeOf((*MockRegistry)(nil).Transactions))
}

// Wallets mocks base method.
func (m *MockRegistry) Wallets() repositories.Wallet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wallets")
	ret0, _ := ret[0].(repositories.Wallet)
	return ret0
}

// Wallets indicates an expected call of Wallets.
func (mr *MockRegistryMockRecorder) Wallets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wallets", reflect.TypeOf((*MockRegistry)(nil).Wallets))
}

// MockWallet is a mock of Wallet interface.
type MockWallet struct {
	ctrl     *gomock.Controller
	recorder *MockWalletMockRecorder
	isgomock struct{}
}

// MockWalletMockRecorder is the mock recorder for MockWallet.
type MockWalletMockRecorder struct {
	mock *MockWallet
}

// NewMockWallet creates a new mock instance.
func NewMockWallet(ctrl *gomock.Controller) *MockWallet {
	mock := &MockWallet{ctrl: ctrl}
	mock.recorder = &MockWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWallet) EXPECT() *MockWalletMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWallet) Create(ctx context.Context, opened *wallet.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opened)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWalletMockRecorder) Create(ctx, opened any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWallet)(nil).Create), ctx, opened)
}

// Find mocks base method.
func (m *MockWallet) Find(ctx context.Context, id uuid.UUID) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockWalletMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockWallet)(nil).Find), ctx, id)
}

// FindByPlayer mocks base method.
func (m *MockWallet) FindByPlayer(ctx context.Context, playerID uuid.UUID, currency money.Currency) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPlayer", ctx, playerID, currency)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPlayer indicates an expected call of FindByPlayer.
func (mr *MockWalletMockRecorder) FindByPlayer(ctx, playerID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPlayer", reflect.TypeOf((*MockWallet)(nil).FindByPlayer), ctx, playerID, currency)
}

// FindForUpdate mocks base method.
func (m *MockWallet) FindForUpdate(ctx context.Context, id uuid.UUID) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindForUpdate", ctx, id)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindForUpdate indicates an expected call of FindForUpdate.
func (mr *MockWalletMockRecorder) FindForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindForUpdate", reflect.TypeOf((*MockWallet)(nil).FindForUpdate), ctx, id)
}

// Update mocks base method.
func (m *MockWallet) Update(ctx context.Context, updated *wallet.Wallet, expectedVersion int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, updated, expectedVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWalletMockRecorder) Update(ctx, updated, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWallet)(nil).Update), ctx, updated, expectedVersion)
}

// MockLedger is a mock of Ledger interface.
type MockLedger struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerMockRecorder
	isgomock struct{}
}

// MockLedgerMockRecorder is the mock recorder for MockLedger.
type MockLedgerMockRecorder struct {
	mock *MockLedger
}

// NewMockLedger creates a new mock instance.
func NewMockLedger(ctrl *gomock.Controller) *MockLedger {
	mock := &MockLedger{ctrl: ctrl}
	mock.recorder = &MockLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedger) EXPECT() *MockLedgerMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockLedger) Append(ctx context.Context, entry wallet.LedgerEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockLedgerMockRecorder) Append(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockLedger)(nil).Append), ctx, entry)
}

// ListAfterVersion mocks base method.
func (m *MockLedger) ListAfterVersion(ctx context.Context, walletID uuid.UUID, afterVersion int64, limit int) ([]wallet.LedgerEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAfterVersion", ctx, walletID, afterVersion, limit)
	ret0, _ := ret[0].([]wallet.LedgerEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAfterVersion indicates an expected call of ListAfterVersion.
func (mr *MockLedgerMockRecorder) ListAfterVersion(ctx, walletID, afterVersion, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAfterVersion", reflect.TypeOf((*MockLedger)(nil).ListAfterVersion), ctx, walletID, afterVersion, limit)
}

// Totals mocks base method.
func (m *MockLedger) Totals(ctx context.Context, walletID uuid.UUID, currency money.Currency) (wallet.LedgerTotals, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Totals", ctx, walletID, currency)
	ret0, _ := ret[0].(wallet.LedgerTotals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Totals indicates an expected call of Totals.
func (mr *MockLedgerMockRecorder) Totals(ctx, walletID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Totals", reflect.TypeOf((*MockLedger)(nil).Totals), ctx, walletID, currency)
}

// MockWagerTransaction is a mock of WagerTransaction interface.
type MockWagerTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockWagerTransactionMockRecorder
	isgomock struct{}
}

// MockWagerTransactionMockRecorder is the mock recorder for MockWagerTransaction.
type MockWagerTransactionMockRecorder struct {
	mock *MockWagerTransaction
}

// NewMockWagerTransaction creates a new mock instance.
func NewMockWagerTransaction(ctrl *gomock.Controller) *MockWagerTransaction {
	mock := &MockWagerTransaction{ctrl: ctrl}
	mock.recorder = &MockWagerTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWagerTransaction) EXPECT() *MockWagerTransactionMockRecorder {
	return m.recorder
}

// ClaimDuePending mocks base method.
func (m *MockWagerTransaction) ClaimDuePending(ctx context.Context, now time.Time, limit int) ([]*wagering.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDuePending", ctx, now, limit)
	ret0, _ := ret[0].([]*wagering.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDuePending indicates an expected call of ClaimDuePending.
func (mr *MockWagerTransactionMockRecorder) ClaimDuePending(ctx, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDuePending", reflect.TypeOf((*MockWagerTransaction)(nil).ClaimDuePending), ctx, now, limit)
}

// CountPending mocks base method.
func (m *MockWagerTransaction) CountPending(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPending", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPending indicates an expected call of CountPending.
func (mr *MockWagerTransactionMockRecorder) CountPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPending", reflect.TypeOf((*MockWagerTransaction)(nil).CountPending), ctx)
}

// FindByExternalID mocks base method.
func (m *MockWagerTransaction) FindByExternalID(ctx context.Context, providerID, externalTransactionID string) (*wagering.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByExternalID", ctx, providerID, externalTransactionID)
	ret0, _ := ret[0].(*wagering.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByExternalID indicates an expected call of FindByExternalID.
func (mr *MockWagerTransactionMockRecorder) FindByExternalID(ctx, providerID, externalTransactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByExternalID", reflect.TypeOf((*MockWagerTransaction)(nil).FindByExternalID), ctx, providerID, externalTransactionID)
}

// FindByID mocks base method.
func (m *MockWagerTransaction) FindByID(ctx context.Context, id uuid.UUID) (*wagering.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*wagering.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockWagerTransactionMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWagerTransaction)(nil).FindByID), ctx, id)
}

// FindByIDForUpdate mocks base method.
func (m *MockWagerTransaction) FindByIDForUpdate(ctx context.Context, id uuid.UUID) (*wagering.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*wagering.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDForUpdate indicates an expected call of FindByIDForUpdate.
func (mr *MockWagerTransactionMockRecorder) FindByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDForUpdate", reflect.TypeOf((*MockWagerTransaction)(nil).FindByIDForUpdate), ctx, id)
}

// FindByIdempotencyKey mocks base method.
func (m *MockWagerTransaction) FindByIdempotencyKey(ctx context.Context, providerID, key string) (*wagering.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdempotencyKey", ctx, providerID, key)
	ret0, _ := ret[0].(*wagering.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdempotencyKey indicates an expected call of FindByIdempotencyKey.
func (mr *MockWagerTransactionMockRecorder) FindByIdempotencyKey(ctx, providerID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdempotencyKey", reflect.TypeOf((*MockWagerTransaction)(nil).FindByIdempotencyKey), ctx, providerID, key)
}

// HasSuccessfulReversal mocks base method.
func (m *MockWagerTransaction) HasSuccessfulReversal(ctx context.Context, referenceTransactionID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSuccessfulReversal", ctx, referenceTransactionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSuccessfulReversal indicates an expected call of HasSuccessfulReversal.
func (mr *MockWagerTransactionMockRecorder) HasSuccessfulReversal(ctx, referenceTransactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSuccessfulReversal", reflect.TypeOf((*MockWagerTransaction)(nil).HasSuccessfulReversal), ctx, referenceTransactionID)
}

// Insert mocks base method.
func (m *MockWagerTransaction) Insert(ctx context.Context, operation *wagering.Transaction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, operation)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockWagerTransactionMockRecorder) Insert(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockWagerTransaction)(nil).Insert), ctx, operation)
}

// Update mocks base method.
func (m *MockWagerTransaction) Update(ctx context.Context, operation *wagering.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWagerTransactionMockRecorder) Update(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWagerTransaction)(nil).Update), ctx, operation)
}

// WakeUpWaitingFor mocks base method.
func (m *MockWagerTransaction) WakeUpWaitingFor(ctx context.Context, providerID, externalTransactionID string, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WakeUpWaitingFor", ctx, providerID, externalTransactionID, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WakeUpWaitingFor indicates an expected call of WakeUpWaitingFor.
func (mr *MockWagerTransactionMockRecorder) WakeUpWaitingFor(ctx, providerID, externalTransactionID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WakeUpWaitingFor", reflect.TypeOf((*MockWagerTransaction)(nil).WakeUpWaitingFor), ctx, providerID, externalTransactionID, now)
}

// MockInbox is a mock of Inbox interface.
type MockInbox struct {
	ctrl     *gomock.Controller
	recorder *MockInboxMockRecorder
	isgomock struct{}
}

// MockInboxMockRecorder is the mock recorder for MockInbox.
type MockInboxMockRecorder struct {
	mock *MockInbox
}

// NewMockInbox creates a new mock instance.
func NewMockInbox(ctrl *gomock.Controller) *MockInbox {
	mock := &MockInbox{ctrl: ctrl}
	mock.recorder = &MockInboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInbox) EXPECT() *MockInboxMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockInbox) Complete(ctx context.Context, consumerName, messageID string, outcome messaging.Outcome, transactionID uuid.UUID, completedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, consumerName, messageID, outcome, transactionID, completedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockInboxMockRecorder) Complete(ctx, consumerName, messageID, outcome, transactionID, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockInbox)(nil).Complete), ctx, consumerName, messageID, outcome, transactionID, completedAt)
}

// Find mocks base method.
func (m *MockInbox) Find(ctx context.Context, consumerName, messageID string) (*messaging.InboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, consumerName, messageID)
	ret0, _ := ret[0].(*messaging.InboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockInboxMockRecorder) Find(ctx, consumerName, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockInbox)(nil).Find), ctx, consumerName, messageID)
}

// Insert mocks base method.
func (m *MockInbox) Insert(ctx context.Context, message messaging.InboxMessage) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, message)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockInboxMockRecorder) Insert(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockInbox)(nil).Insert), ctx, message)
}

// MockOutbox is a mock of Outbox interface.
type MockOutbox struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxMockRecorder
	isgomock struct{}
}

// MockOutboxMockRecorder is the mock recorder for MockOutbox.
type MockOutboxMockRecorder struct {
	mock *MockOutbox
}

// NewMockOutbox creates a new mock instance.
func NewMockOutbox(ctrl *gomock.Controller) *MockOutbox {
	mock := &MockOutbox{ctrl: ctrl}
	mock.recorder = &MockOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutbox) EXPECT() *MockOutboxMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockOutbox) Append(ctx context.Context, outboxEvent messaging.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, outboxEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockOutboxMockRecorder) Append(ctx, outboxEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockOutbox)(nil).Append), ctx, outboxEvent)
}

// Claim mocks base method.
func (m *MockOutbox) Claim(ctx context.Context, owner string, now time.Time, lease time.Duration, limit int) ([]messaging.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", ctx, owner, now, lease, limit)
	ret0, _ := ret[0].([]messaging.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockOutboxMockRecorder) Claim(ctx, owner, now, lease, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockOutbox)(nil).Claim), ctx, owner, now, lease, limit)
}

// MarkFailed mocks base method.
func (m *MockOutbox) MarkFailed(ctx context.Context, receipt messaging.Receipt, reason string, nextAttemptAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, receipt, reason, nextAttemptAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxMockRecorder) MarkFailed(ctx, receipt, reason, nextAttemptAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutbox)(nil).MarkFailed), ctx, receipt, reason, nextAttemptAt)
}

// MarkPublished mocks base method.
func (m *MockOutbox) MarkPublished(ctx context.Context, receipt messaging.Receipt, publishedAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, receipt, publishedAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxMockRecorder) MarkPublished(ctx, receipt, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutbox)(nil).MarkPublished), ctx, receipt, publishedAt)
}

// PendingStats mocks base method.
func (m *MockOutbox) PendingStats(ctx context.Context, now time.Time) (messaging.PendingStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingStats", ctx, now)
	ret0, _ := ret[0].(messaging.PendingStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingStats indicates an expected call of PendingStats.
func (mr *MockOutboxMockRecorder) PendingStats(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingStats", reflect.TypeOf((*MockOutbox)(nil).PendingStats), ctx, now)
}
