// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/matheusj989/wagering-wallet-service/internal/application/usecase (interfaces: OpenWallet,ProcessWagerTransaction,FindWallet,ListWalletLedger,ReconcileWallet,FindWagerTransaction,RetryPendingReference,PublishOutbox)
//
// Generated by this command:
//
//	mockgen -destination=usecase.go -package=mocks github.com/matheusj989/wagering-wallet-service/internal/application/usecase OpenWallet,ProcessWagerTransaction,FindWallet,ListWalletLedger,ReconcileWallet,FindWagerTransaction,RetryPendingReference,PublishOutbox
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/matheusj989/wagering-wallet-service/internal/application/dto"
	wagering "github.com/matheusj989/wagering-wallet-service/internal/domain/wagering"
	wallet "github.com/matheusj989/wagering-wallet-service/internal/domain/wallet"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenWallet is a mock of OpenWallet interface.
type MockOpenWallet struct {
	ctrl     *gomock.Controller
	recorder *MockOpenWalletMockRecorder
	isgomock struct{}
}

// MockOpenWalletMockRecorder is the mock recorder for MockOpenWallet.
type MockOpenWalletMockRecorder struct {
	mock *MockOpenWallet
}

// NewMockOpenWallet creates a new mock instance.
func NewMockOpenWallet(ctrl *gomock.Controller) *MockOpenWallet {
	mock := &MockOpenWallet{ctrl: ctrl}
	mock.recorder = &MockOpenWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenWallet) EXPECT() *MockOpenWalletMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockOpenWallet) Execute(ctx context.Context, input dto.OpenWalletInput) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockOpenWalletMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockOpenWallet)(nil).Execute), ctx, input)
}

// MockProcessWagerTransaction is a mock of ProcessWagerTransaction interface.
type MockProcessWagerTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockProcessWagerTransactionMockRecorder
	isgomock struct{}
}

// MockProcessWagerTransactionMockRecorder is the mock recorder for MockProcessWagerTransaction.
type MockProcessWagerTransactionMockRecorder struct {
	mock *MockProcessWagerTransaction
}

// NewMockProcessWagerTransaction creates a new mock instance.
func NewMockProcessWagerTransaction(ctrl *gomock.Controller) *MockProcessWagerTransaction {
	mock := &MockProcessWagerTransaction{ctrl: ctrl}
	mock.recorder = &MockProcessWagerTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessWagerTransaction) EXPECT() *MockProcessWagerTransactionMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProcessWagerTransaction) Execute(ctx context.Context, input dto.ProcessWagerInput) (dto.ProcessWagerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(dto.ProcessWagerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockProcessWagerTransactionMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProcessWagerTransaction)(nil).Execute), ctx, input)
}

// MockFindWallet is a mock of FindWallet interface.
type MockFindWallet struct {
	ctrl     *gomock.Controller
	recorder *MockFindWalletMockRecorder
	isgomock struct{}
}

// MockFindWalletMockRecorder is the mock recorder for MockFindWallet.
type MockFindWalletMockRecorder struct {
	mock *MockFindWallet
}

// NewMockFindWallet creates a new mock instance.
func NewMockFindWallet(ctrl *gomock.Controller) *MockFindWallet {
	mock := &MockFindWallet{ctrl: ctrl}
	mock.recorder = &MockFindWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindWallet) EXPECT() *MockFindWalletMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFindWallet) Execute(ctx context.Context, walletID uuid.UUID) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, walletID)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFindWalletMockRecorder) Execute(ctx, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFindWallet)(nil).Execute), ctx, walletID)
}

// MockListWalletLedger is a mock of ListWalletLedger interface.
type MockListWalletLedger struct {
	ctrl     *gomock.Controller
	recorder *MockListWalletLedgerMockRecorder
	isgomock struct{}
}

// MockListWalletLedgerMockRecorder is the mock recorder for MockListWalletLedger.
type MockListWalletLedgerMockRecorder struct {
	mock *MockListWalletLedger
}

// NewMockListWalletLedger creates a new mock instance.
func NewMockListWalletLedger(ctrl *gomock.Controller) *MockListWalletLedger {
	mock := &MockListWalletLedger{ctrl: ctrl}
	mock.recorder = &MockListWalletLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListWalletLedger) EXPECT() *MockListWalletLedgerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListWalletLedger) Execute(ctx context.Context, input dto.ListLedgerInput) (dto.LedgerPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(dto.LedgerPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListWalletLedgerMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListWalletLedger)(nil).Execute), ctx, input)
}

// MockReconcileWallet is a mock of ReconcileWallet interface.
type MockReconcileWallet struct {
	ctrl     *gomock.Controller
	recorder *MockReconcileWalletMockRecorder
	isgomock struct{}
}

// MockReconcileWalletMockRecorder is the mock recorder for MockReconcileWallet.
type MockReconcileWalletMockRecorder struct {
	mock *MockReconcileWallet
}

// NewMockReconcileWallet creates a new mock instance.
func NewMockReconcileWallet(ctrl *gomock.Controller) *MockReconcileWallet {
	mock := &MockReconcileWallet{ctrl: ctrl}
	mock.recorder = &MockReconcileWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconcileWallet) EXPECT() *MockReconcileWalletMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockReconcileWallet) Execute(ctx context.Context, walletID uuid.UUID) (dto.Reconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, walletID)
	ret0, _ := ret[0].(dto.Reconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockReconcileWalletMockRecorder) Execute(ctx, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockReconcileWallet)(nil).Execute), ctx, walletID)
}

// MockFindWagerTransaction is a mock of FindWagerTransaction interface.
type MockFindWagerTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockFindWagerTransactionMockRecorder
	isgomock struct{}
}

// MockFindWagerTransactionMockRecorder is the mock recorder for MockFindWagerTransaction.
type MockFindWagerTransactionMockRecorder struct {
	mock *MockFindWagerTransaction
}

// NewMockFindWagerTransaction creates a new mock instance.
func NewMockFindWagerTransaction(ctrl *gomock.Controller) *MockFindWagerTransaction {
	mock := &MockFindWagerTransaction{ctrl: ctrl}
	mock.recorder = &MockFindWagerTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindWagerTransaction) EXPECT() *MockFindWagerTransactionMockRecorder {
	return m.recorder
}

// ByExternalID mocks base method.
func (m *MockFindWagerTransaction) ByExternalID(ctx context.Context, providerID, externalTransactionID string) (*wagering.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByExternalID", ctx, providerID, externalTransactionID)
	ret0, _ := ret[0].(*wagering.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByExternalID indicates an expected call of ByExternalID.
func (mr *MockFindWagerTransactionMockRecorder) ByExternalID(ctx, providerID, externalTransactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByExternalID", reflect.TypeOf((*MockFindWagerTransaction)(nil).ByExternalID), ctx, providerID, externalTransactionID)
}

// ByID mocks base method.
func (m *MockFindWagerTransaction) ByID(ctx context.Context, transactionID uuid.UUID) (*wagering.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, transactionID)
	ret0, _ := ret[0].(*wagering.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockFindWagerTransactionMockRecorder) ByID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockFindWagerTransaction)(nil).ByID), ctx, transactionID)
}

// MockRetryPendingReference is a mock of RetryPendingReference interface.
type MockRetryPendingReference struct {
	ctrl     *gomock.Controller
	recorder *MockRetryPendingReferenceMockRecorder
	isgomock struct{}
}

// MockRetryPendingReferenceMockRecorder is the mock recorder for MockRetryPendingReference.
type MockRetryPendingReferenceMockRecorder struct {
	mock *MockRetryPendingReference
}

// NewMockRetryPendingReference creates a new mock instance.
func NewMockRetryPendingReference(ctrl *gomock.Controller) *MockRetryPendingReference {
	mock := &MockRetryPendingReference{ctrl: ctrl}
	mock.recorder = &MockRetryPendingReferenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetryPendingReference) EXPECT() *MockRetryPendingReferenceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRetryPendingReference) Execute(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRetryPendingReferenceMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRetryPendingReference)(nil).Execute), ctx)
}

// ReportPending mocks base method.
func (m *MockRetryPendingReference) ReportPending(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportPending", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportPending indicates an expected call of ReportPending.
func (mr *MockRetryPendingReferenceMockRecorder) ReportPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportPending", reflect.TypeOf((*MockRetryPendingReference)(nil).ReportPending), ctx)
}

// MockPublishOutbox is a mock of PublishOutbox interface.
type MockPublishOutbox struct {
	ctrl     *gomock.Controller
	recorder *MockPublishOutboxMockRecorder
	isgomock struct{}
}

// MockPublishOutboxMockRecorder is the mock recorder for MockPublishOutbox.
type MockPublishOutboxMockRecorder struct {
	mock *MockPublishOutbox
}

// NewMockPublishOutbox creates a new mock instance.
func NewMockPublishOutbox(ctrl *gomock.Controller) *MockPublishOutbox {
	mock := &MockPublishOutbox{ctrl: ctrl}
	mock.recorder = &MockPublishOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublishOutbox) EXPECT() *MockPublishOutboxMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPublishOutbox) Execute(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPublishOutboxMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPublishOutbox)(nil).Execute), ctx)
}

// ReportPending mocks base method.
func (m *MockPublishOutbox) ReportPending(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportPending", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportPending indicates an expected call of ReportPending.
func (mr *MockPublishOutboxMockRecorder) ReportPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportPending", reflect.TypeOf((*MockPublishOutbox)(nil).ReportPending), ctx)
}
